[2025-10-29T00:10:36.124+0000] {processor.py:161} INFO - Started process (PID=708) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:10:36.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T00:10:36.131+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:10:36.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:10:36.139+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:10:36.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T00:10:36.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:10:36.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.064 seconds
[2025-10-29T00:12:42.742+0000] {processor.py:161} INFO - Started process (PID=709) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:12:42.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T00:12:42.748+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:12:42.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:12:42.759+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:12:42.756+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T00:12:42.759+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:12:42.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.070 seconds
[2025-10-29T00:13:36.994+0000] {processor.py:161} INFO - Started process (PID=710) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:13:37.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T00:13:37.007+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:13:37.006+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:13:37.020+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:13:37.017+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T00:13:37.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:13:37.058+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.099 seconds
[2025-10-29T00:26:06.379+0000] {processor.py:161} INFO - Started process (PID=711) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:26:06.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T00:26:06.387+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:26:06.386+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:26:06.398+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:26:06.396+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T00:26:06.399+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:26:06.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.052 seconds
[2025-10-29T00:27:33.096+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:27:33.099+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T00:27:33.111+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:27:33.109+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:27:33.124+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:27:33.121+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T00:27:33.124+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:27:33.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.077 seconds
[2025-10-29T00:40:24.254+0000] {processor.py:161} INFO - Started process (PID=713) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:40:24.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T00:40:24.266+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:40:24.265+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:40:24.276+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:40:24.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T00:40:24.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:40:24.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.078 seconds
[2025-10-29T00:59:17.595+0000] {processor.py:161} INFO - Started process (PID=714) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:59:17.603+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T00:59:17.612+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:59:17.610+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:59:17.667+0000] {logging_mixin.py:188} INFO - [2025-10-29T00:59:17.662+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T00:59:17.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T00:59:17.752+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.173 seconds
[2025-10-29T01:28:15.632+0000] {processor.py:161} INFO - Started process (PID=715) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:28:15.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:28:15.638+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:28:15.637+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:28:15.654+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:28:15.652+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:28:15.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:28:15.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.072 seconds
[2025-10-29T01:28:45.899+0000] {processor.py:161} INFO - Started process (PID=716) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:28:45.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:28:45.911+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:28:45.909+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:28:45.924+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:28:45.922+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:28:45.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:28:45.958+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.069 seconds
[2025-10-29T01:29:16.225+0000] {processor.py:161} INFO - Started process (PID=717) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:29:16.228+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:29:16.233+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:29:16.232+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:29:16.243+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:29:16.241+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:29:16.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:29:16.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.075 seconds
[2025-10-29T01:29:46.528+0000] {processor.py:161} INFO - Started process (PID=718) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:29:46.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:29:46.537+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:29:46.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:29:46.551+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:29:46.548+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:29:46.552+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:29:46.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.064 seconds
[2025-10-29T01:30:16.855+0000] {processor.py:161} INFO - Started process (PID=719) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:30:16.858+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:30:16.862+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:30:16.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:30:16.874+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:30:16.870+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:30:16.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:30:16.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.072 seconds
[2025-10-29T01:30:47.130+0000] {processor.py:161} INFO - Started process (PID=720) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:30:47.132+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:30:47.135+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:30:47.134+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:30:47.141+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:30:47.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:30:47.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:30:47.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.047 seconds
[2025-10-29T01:31:17.428+0000] {processor.py:161} INFO - Started process (PID=721) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:31:17.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:31:17.437+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:31:17.436+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:31:17.447+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:31:17.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:31:17.447+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:31:17.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.070 seconds
[2025-10-29T01:31:47.730+0000] {processor.py:161} INFO - Started process (PID=722) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:31:47.732+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:31:47.733+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:31:47.733+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:31:47.737+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:31:47.736+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:31:47.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:31:47.754+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.034 seconds
[2025-10-29T01:32:18.058+0000] {processor.py:161} INFO - Started process (PID=723) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:32:18.061+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:32:18.070+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:32:18.067+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:32:18.090+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:32:18.088+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:32:18.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:32:18.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.080 seconds
[2025-10-29T01:32:48.368+0000] {processor.py:161} INFO - Started process (PID=724) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:32:48.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:32:48.373+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:32:48.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:32:48.382+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:32:48.380+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:32:48.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:32:48.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.056 seconds
[2025-10-29T01:33:19.159+0000] {processor.py:161} INFO - Started process (PID=725) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:33:19.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:33:19.176+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:33:19.175+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:33:19.184+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:33:19.182+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:33:19.185+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:33:19.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.065 seconds
[2025-10-29T01:33:49.426+0000] {processor.py:161} INFO - Started process (PID=726) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:33:49.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:33:49.432+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:33:49.432+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:33:49.441+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:33:49.440+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:33:49.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:33:49.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.056 seconds
[2025-10-29T01:34:19.721+0000] {processor.py:161} INFO - Started process (PID=727) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:34:19.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:34:19.726+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:34:19.725+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:34:19.734+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:34:19.732+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:34:19.735+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:34:19.761+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.049 seconds
[2025-10-29T01:34:50.072+0000] {processor.py:161} INFO - Started process (PID=728) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:34:50.074+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:34:50.077+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:34:50.077+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:34:50.086+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:34:50.084+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:34:50.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:34:50.122+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.079 seconds
[2025-10-29T01:35:20.370+0000] {processor.py:161} INFO - Started process (PID=729) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:35:20.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:35:20.378+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:35:20.377+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:35:20.390+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:35:20.387+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:35:20.390+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:35:20.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.062 seconds
[2025-10-29T01:35:50.645+0000] {processor.py:161} INFO - Started process (PID=730) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:35:50.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:35:50.648+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:35:50.648+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:35:50.656+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:35:50.654+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:35:50.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:35:50.682+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.046 seconds
[2025-10-29T01:36:20.948+0000] {processor.py:161} INFO - Started process (PID=731) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:36:20.950+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:36:20.954+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:36:20.954+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:36:20.964+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:36:20.962+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:36:20.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:36:20.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.064 seconds
[2025-10-29T01:36:51.217+0000] {processor.py:161} INFO - Started process (PID=732) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:36:51.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:36:51.223+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:36:51.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:36:51.232+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:36:51.229+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:36:51.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:36:51.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.056 seconds
[2025-10-29T01:37:21.501+0000] {processor.py:161} INFO - Started process (PID=733) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:37:21.504+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:37:21.507+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:37:21.507+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:37:21.516+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:37:21.514+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:37:21.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:37:21.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.054 seconds
[2025-10-29T01:37:51.832+0000] {processor.py:161} INFO - Started process (PID=734) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:37:51.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:37:51.841+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:37:51.840+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:37:51.850+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:37:51.848+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:37:51.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:37:51.880+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.063 seconds
[2025-10-29T01:38:22.137+0000] {processor.py:161} INFO - Started process (PID=735) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:38:22.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:38:22.143+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:38:22.142+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:38:22.154+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:38:22.151+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:38:22.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:38:22.181+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.053 seconds
[2025-10-29T01:38:52.428+0000] {processor.py:161} INFO - Started process (PID=736) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:38:52.429+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:38:52.432+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:38:52.432+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:38:52.438+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:38:52.436+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:38:52.438+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:38:52.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.045 seconds
[2025-10-29T01:39:22.691+0000] {processor.py:161} INFO - Started process (PID=737) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:39:22.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:39:22.696+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:39:22.695+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:39:22.704+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:39:22.702+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:39:22.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:39:22.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.046 seconds
[2025-10-29T01:39:52.978+0000] {processor.py:161} INFO - Started process (PID=738) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:39:52.982+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:39:52.986+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:39:52.985+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:39:52.995+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:39:52.992+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:39:52.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:39:53.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.055 seconds
[2025-10-29T01:40:23.255+0000] {processor.py:161} INFO - Started process (PID=739) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:40:23.256+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:40:23.258+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:40:23.258+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:40:23.265+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:40:23.263+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:40:23.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:40:23.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.040 seconds
[2025-10-29T01:40:53.512+0000] {processor.py:161} INFO - Started process (PID=740) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:40:53.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:40:53.517+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:40:53.516+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:40:53.525+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:40:53.523+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:40:53.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:40:53.551+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.047 seconds
[2025-10-29T01:41:23.778+0000] {processor.py:161} INFO - Started process (PID=741) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:41:23.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:41:23.781+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:41:23.781+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:41:23.786+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:41:23.785+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:41:23.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:41:23.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.029 seconds
[2025-10-29T01:41:54.016+0000] {processor.py:161} INFO - Started process (PID=742) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:41:54.017+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:41:54.019+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:41:54.018+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:41:54.024+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:41:54.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:41:54.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:41:54.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.033 seconds
[2025-10-29T01:42:24.309+0000] {processor.py:161} INFO - Started process (PID=743) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:42:24.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:42:24.314+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:42:24.314+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:42:24.323+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:42:24.321+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:42:24.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:42:24.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.053 seconds
[2025-10-29T01:42:54.554+0000] {processor.py:161} INFO - Started process (PID=744) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:42:54.556+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:42:54.560+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:42:54.560+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:42:54.569+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:42:54.567+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:42:54.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:42:54.595+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.056 seconds
[2025-10-29T01:43:24.831+0000] {processor.py:161} INFO - Started process (PID=745) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:43:24.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:43:24.834+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:43:24.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:43:24.841+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:43:24.839+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:43:24.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:43:24.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.039 seconds
[2025-10-29T01:43:55.125+0000] {processor.py:161} INFO - Started process (PID=746) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:43:55.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:43:55.131+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:43:55.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:43:55.142+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:43:55.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:43:55.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:43:55.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.064 seconds
[2025-10-29T01:44:25.403+0000] {processor.py:161} INFO - Started process (PID=747) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:44:25.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:44:25.405+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:44:25.405+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:44:25.411+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:44:25.410+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:44:25.411+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:44:25.427+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.029 seconds
[2025-10-29T01:44:55.690+0000] {processor.py:161} INFO - Started process (PID=748) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:44:55.691+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:44:55.695+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:44:55.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:44:55.704+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:44:55.701+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:44:55.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:44:55.736+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.056 seconds
[2025-10-29T01:45:25.973+0000] {processor.py:161} INFO - Started process (PID=749) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:45:25.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:45:25.975+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:45:25.975+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:45:25.980+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:45:25.979+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:45:25.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:45:25.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.027 seconds
[2025-10-29T01:45:56.406+0000] {processor.py:161} INFO - Started process (PID=750) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:45:56.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:45:56.414+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:45:56.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:45:56.426+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:45:56.423+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:45:56.426+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:45:56.459+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.067 seconds
[2025-10-29T01:46:26.743+0000] {processor.py:161} INFO - Started process (PID=751) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:46:26.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:46:26.753+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:46:26.752+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:46:26.764+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:46:26.762+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:46:26.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:46:26.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.075 seconds
[2025-10-29T01:46:57.088+0000] {processor.py:161} INFO - Started process (PID=752) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:46:57.090+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:46:57.096+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:46:57.095+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:46:57.107+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:46:57.104+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:46:57.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:46:57.150+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.089 seconds
[2025-10-29T01:47:27.363+0000] {processor.py:161} INFO - Started process (PID=753) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:47:27.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:47:27.367+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:47:27.367+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:47:27.375+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:47:27.373+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:47:27.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:47:27.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.052 seconds
[2025-10-29T01:47:57.666+0000] {processor.py:161} INFO - Started process (PID=754) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:47:57.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:47:57.672+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:47:57.671+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:47:57.685+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:47:57.683+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:47:57.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:47:57.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.062 seconds
[2025-10-29T01:48:27.974+0000] {processor.py:161} INFO - Started process (PID=755) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:48:27.976+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:48:27.980+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:48:27.980+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:48:27.989+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:48:27.987+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:48:27.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:48:28.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.067 seconds
[2025-10-29T01:48:58.262+0000] {processor.py:161} INFO - Started process (PID=756) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:48:58.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:48:58.268+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:48:58.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:48:58.278+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:48:58.275+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:48:58.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:48:58.316+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.071 seconds
[2025-10-29T01:49:28.583+0000] {processor.py:161} INFO - Started process (PID=757) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:49:28.585+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:49:28.588+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:49:28.587+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:49:28.595+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:49:28.593+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:49:28.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:49:28.617+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.062 seconds
[2025-10-29T01:49:58.871+0000] {processor.py:161} INFO - Started process (PID=758) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:49:58.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:49:58.878+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:49:58.878+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:49:58.888+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:49:58.886+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:49:58.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:49:58.917+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.060 seconds
[2025-10-29T01:50:29.169+0000] {processor.py:161} INFO - Started process (PID=759) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:50:29.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:50:29.172+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:50:29.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:50:29.179+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:50:29.177+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:50:29.179+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:50:29.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.041 seconds
[2025-10-29T01:50:59.470+0000] {processor.py:161} INFO - Started process (PID=760) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:50:59.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:50:59.478+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:50:59.478+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:50:59.488+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:50:59.486+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:50:59.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:50:59.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.059 seconds
[2025-10-29T01:51:29.829+0000] {processor.py:161} INFO - Started process (PID=761) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:51:29.833+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:51:29.859+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:51:29.858+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:51:29.875+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:51:29.871+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:51:29.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:51:29.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.115 seconds
[2025-10-29T01:52:00.101+0000] {processor.py:161} INFO - Started process (PID=762) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:52:00.103+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:52:00.106+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:52:00.105+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:52:00.122+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:52:00.118+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:52:00.122+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:52:00.159+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.072 seconds
[2025-10-29T01:52:30.428+0000] {processor.py:161} INFO - Started process (PID=763) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:52:30.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:52:30.436+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:52:30.436+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:52:30.448+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:52:30.445+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:52:30.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:52:30.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.068 seconds
[2025-10-29T01:53:00.702+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:53:00.704+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:53:00.707+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:53:00.706+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:53:00.714+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:53:00.712+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:53:00.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:53:00.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.050 seconds
[2025-10-29T01:53:31.013+0000] {processor.py:161} INFO - Started process (PID=765) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:53:31.014+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:53:31.016+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:53:31.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:53:31.021+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:53:31.020+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:53:31.022+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:53:31.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.035 seconds
[2025-10-29T01:54:01.308+0000] {processor.py:161} INFO - Started process (PID=766) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:54:01.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:54:01.313+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:54:01.312+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:54:01.322+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:54:01.320+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:54:01.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:54:01.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.051 seconds
[2025-10-29T01:54:31.608+0000] {processor.py:161} INFO - Started process (PID=767) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:54:31.608+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:54:31.610+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:54:31.610+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:54:31.616+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:54:31.614+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:54:31.616+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:54:31.636+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.035 seconds
[2025-10-29T01:55:01.895+0000] {processor.py:161} INFO - Started process (PID=768) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:55:01.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:55:01.901+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:55:01.900+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:55:01.911+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:55:01.909+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:55:01.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:55:01.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.058 seconds
[2025-10-29T01:55:32.215+0000] {processor.py:161} INFO - Started process (PID=769) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:55:32.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:55:32.223+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:55:32.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:55:32.237+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:55:32.234+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:55:32.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:55:32.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.073 seconds
[2025-10-29T01:56:02.461+0000] {processor.py:161} INFO - Started process (PID=770) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:56:02.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:56:02.465+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:56:02.465+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:56:02.472+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:56:02.471+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:56:02.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:56:02.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.051 seconds
[2025-10-29T01:56:32.729+0000] {processor.py:161} INFO - Started process (PID=771) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:56:32.731+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:56:32.735+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:56:32.734+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:56:32.744+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:56:32.742+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:56:32.745+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:56:32.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.145 seconds
[2025-10-29T01:57:03.019+0000] {processor.py:161} INFO - Started process (PID=772) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:57:03.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:57:03.025+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:57:03.024+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:57:03.031+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:57:03.029+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:57:03.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:57:03.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.052 seconds
[2025-10-29T01:57:33.269+0000] {processor.py:161} INFO - Started process (PID=773) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:57:33.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:57:33.271+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:57:33.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:57:33.276+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:57:33.275+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:57:33.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:57:33.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.028 seconds
[2025-10-29T01:58:03.527+0000] {processor.py:161} INFO - Started process (PID=774) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:58:03.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:58:03.531+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:58:03.530+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:58:03.537+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:58:03.535+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:58:03.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:58:03.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.039 seconds
[2025-10-29T01:58:33.831+0000] {processor.py:161} INFO - Started process (PID=775) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:58:33.832+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:58:33.834+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:58:33.834+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:58:33.839+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:58:33.837+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:58:33.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:58:33.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.029 seconds
[2025-10-29T01:59:04.130+0000] {processor.py:161} INFO - Started process (PID=776) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:59:04.131+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:59:04.133+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:59:04.133+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:59:04.139+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:59:04.137+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:59:04.139+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:59:04.155+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.032 seconds
[2025-10-29T01:59:34.559+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:59:34.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T01:59:34.566+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:59:34.566+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:59:34.575+0000] {logging_mixin.py:188} INFO - [2025-10-29T01:59:34.573+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T01:59:34.575+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T01:59:34.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.052 seconds
[2025-10-29T02:00:04.833+0000] {processor.py:161} INFO - Started process (PID=778) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:00:04.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:00:04.837+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:00:04.837+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:00:04.844+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:00:04.842+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:00:04.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:00:04.868+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.043 seconds
[2025-10-29T02:00:35.131+0000] {processor.py:161} INFO - Started process (PID=779) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:00:35.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:00:35.137+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:00:35.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:00:35.146+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:00:35.144+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:00:35.147+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:00:35.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.053 seconds
[2025-10-29T02:01:05.396+0000] {processor.py:161} INFO - Started process (PID=780) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:01:05.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:01:05.403+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:01:05.402+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:01:05.412+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:01:05.409+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:01:05.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:01:05.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.053 seconds
[2025-10-29T02:01:35.669+0000] {processor.py:161} INFO - Started process (PID=781) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:01:35.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:01:35.674+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:01:35.673+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:01:35.682+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:01:35.680+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:01:35.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:01:35.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.047 seconds
[2025-10-29T02:02:05.962+0000] {processor.py:161} INFO - Started process (PID=782) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:02:05.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:02:05.968+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:02:05.967+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:02:05.977+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:02:05.975+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:02:05.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:02:06.006+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.072 seconds
[2025-10-29T02:02:36.218+0000] {processor.py:161} INFO - Started process (PID=783) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:02:36.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:02:36.223+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:02:36.223+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:02:36.233+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:02:36.231+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:02:36.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:02:36.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.054 seconds
[2025-10-29T02:03:06.505+0000] {processor.py:161} INFO - Started process (PID=784) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:03:06.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:03:06.510+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:03:06.510+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:03:06.522+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:03:06.516+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:03:06.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:03:06.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.054 seconds
[2025-10-29T02:03:36.816+0000] {processor.py:161} INFO - Started process (PID=785) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:03:36.819+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:03:36.824+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:03:36.823+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:03:36.838+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:03:36.832+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:03:36.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:03:36.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.087 seconds
[2025-10-29T02:04:07.097+0000] {processor.py:161} INFO - Started process (PID=786) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:04:07.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:04:07.107+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:04:07.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:04:07.116+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:04:07.114+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:04:07.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:04:07.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.071 seconds
[2025-10-29T02:04:37.432+0000] {processor.py:161} INFO - Started process (PID=787) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:04:37.435+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:04:37.438+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:04:37.437+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:04:37.451+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:04:37.449+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:04:37.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:04:37.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.065 seconds
[2025-10-29T02:05:07.715+0000] {processor.py:161} INFO - Started process (PID=788) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:05:07.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:05:07.721+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:05:07.721+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:05:07.731+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:05:07.728+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:05:07.732+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:05:07.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.065 seconds
[2025-10-29T02:05:38.046+0000] {processor.py:161} INFO - Started process (PID=789) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:05:38.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:05:38.065+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:05:38.063+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:05:38.075+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:05:38.072+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:05:38.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:05:38.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.080 seconds
[2025-10-29T02:06:08.357+0000] {processor.py:161} INFO - Started process (PID=790) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:06:08.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:06:08.363+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:06:08.362+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:06:08.371+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:06:08.370+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:06:08.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:06:08.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.052 seconds
[2025-10-29T02:06:38.649+0000] {processor.py:161} INFO - Started process (PID=791) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:06:38.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:06:38.654+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:06:38.654+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:06:38.664+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:06:38.661+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:06:38.665+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:06:38.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.067 seconds
[2025-10-29T02:07:08.949+0000] {processor.py:161} INFO - Started process (PID=792) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:07:08.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:07:08.955+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:07:08.954+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:07:08.964+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:07:08.961+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:07:08.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:07:08.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.049 seconds
[2025-10-29T02:07:39.202+0000] {processor.py:161} INFO - Started process (PID=793) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:07:39.204+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:07:39.207+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:07:39.206+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:07:39.213+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:07:39.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:07:39.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:07:39.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.508 seconds
[2025-10-29T02:08:10.122+0000] {processor.py:161} INFO - Started process (PID=794) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:08:10.125+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:08:10.129+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:08:10.128+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:08:10.135+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:08:10.133+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:08:10.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:08:10.162+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.053 seconds
[2025-10-29T02:08:40.394+0000] {processor.py:161} INFO - Started process (PID=795) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:08:40.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:08:40.398+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:08:40.398+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:08:40.406+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:08:40.404+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:08:40.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:08:40.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.053 seconds
[2025-10-29T02:09:10.697+0000] {processor.py:161} INFO - Started process (PID=796) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:09:10.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:09:10.704+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:09:10.703+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:09:10.713+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:09:10.711+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:09:10.714+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:09:10.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.053 seconds
[2025-10-29T02:09:41.032+0000] {processor.py:161} INFO - Started process (PID=797) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:09:41.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:09:41.040+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:09:41.039+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:09:41.052+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:09:41.050+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:09:41.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:09:41.079+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.060 seconds
[2025-10-29T02:10:11.356+0000] {processor.py:161} INFO - Started process (PID=798) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:10:11.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:10:11.364+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:10:11.364+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:10:11.374+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:10:11.372+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:10:11.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:10:11.408+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.065 seconds
[2025-10-29T02:10:41.667+0000] {processor.py:161} INFO - Started process (PID=799) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:10:41.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:10:41.672+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:10:41.672+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:10:41.681+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:10:41.679+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:10:41.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:10:41.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.048 seconds
[2025-10-29T02:11:11.924+0000] {processor.py:161} INFO - Started process (PID=800) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:11:11.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:11:11.930+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:11:11.929+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:11:11.938+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:11:11.936+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:11:11.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:11:11.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.048 seconds
[2025-10-29T02:11:42.246+0000] {processor.py:161} INFO - Started process (PID=801) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:11:42.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:11:42.253+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:11:42.253+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:11:42.264+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:11:42.262+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:11:42.265+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:11:42.303+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.070 seconds
[2025-10-29T02:12:12.546+0000] {processor.py:161} INFO - Started process (PID=802) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:12:12.549+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:12:12.555+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:12:12.554+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:12:12.565+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:12:12.562+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:12:12.565+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:12:12.594+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.060 seconds
[2025-10-29T02:12:43.043+0000] {processor.py:161} INFO - Started process (PID=803) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:12:43.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:12:43.052+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:12:43.051+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:12:43.063+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:12:43.061+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:12:43.064+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:12:43.093+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.068 seconds
[2025-10-29T02:13:13.347+0000] {processor.py:161} INFO - Started process (PID=804) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:13:13.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:13:13.355+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:13:13.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:13:13.366+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:13:13.363+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:13:13.366+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:13:13.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.064 seconds
[2025-10-29T02:13:43.662+0000] {processor.py:161} INFO - Started process (PID=805) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:13:43.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:13:43.669+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:13:43.669+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:13:43.678+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:13:43.676+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:13:43.679+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:13:43.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.058 seconds
[2025-10-29T02:14:13.948+0000] {processor.py:161} INFO - Started process (PID=806) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:14:13.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:14:13.951+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:14:13.951+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:14:13.956+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:14:13.955+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:14:13.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:14:13.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.030 seconds
[2025-10-29T02:14:44.264+0000] {processor.py:161} INFO - Started process (PID=807) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:14:44.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:14:44.269+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:14:44.269+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:14:44.277+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:14:44.275+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:14:44.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:14:44.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.059 seconds
[2025-10-29T02:15:14.543+0000] {processor.py:161} INFO - Started process (PID=808) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:15:14.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:15:14.546+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:15:14.545+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:15:14.550+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:15:14.549+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:15:14.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:15:14.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.032 seconds
[2025-10-29T02:15:44.809+0000] {processor.py:161} INFO - Started process (PID=809) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:15:44.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:15:44.813+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:15:44.812+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:15:44.820+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:15:44.818+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:15:44.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:15:44.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.041 seconds
[2025-10-29T02:16:15.039+0000] {processor.py:161} INFO - Started process (PID=810) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:16:15.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:16:15.041+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:16:15.041+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:16:15.045+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:16:15.044+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:16:15.045+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:16:15.060+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.026 seconds
[2025-10-29T02:16:45.380+0000] {processor.py:161} INFO - Started process (PID=811) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:16:45.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:16:45.388+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:16:45.387+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:16:45.399+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:16:45.397+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:16:45.400+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:16:45.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.073 seconds
[2025-10-29T02:17:15.651+0000] {processor.py:161} INFO - Started process (PID=812) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:17:15.653+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:17:15.657+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:17:15.656+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:17:15.668+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:17:15.665+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:17:15.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:17:15.698+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.061 seconds
[2025-10-29T02:17:45.893+0000] {processor.py:161} INFO - Started process (PID=813) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:17:45.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:17:45.899+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:17:45.898+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:17:45.907+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:17:45.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:17:45.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:17:45.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.053 seconds
[2025-10-29T02:18:16.317+0000] {processor.py:161} INFO - Started process (PID=814) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:18:16.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:18:16.322+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:18:16.322+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:18:16.341+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:18:16.335+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:18:16.342+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:18:16.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.070 seconds
[2025-10-29T02:18:46.600+0000] {processor.py:161} INFO - Started process (PID=815) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:18:46.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:18:46.604+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:18:46.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:18:46.611+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:18:46.609+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:18:46.612+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:18:46.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.045 seconds
[2025-10-29T02:19:16.858+0000] {processor.py:161} INFO - Started process (PID=816) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:19:16.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:19:16.860+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:19:16.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:19:16.864+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:19:16.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:19:16.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:19:16.875+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.022 seconds
[2025-10-29T02:19:47.180+0000] {processor.py:161} INFO - Started process (PID=817) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:19:47.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:19:47.186+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:19:47.185+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:19:47.193+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:19:47.191+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:19:47.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:19:47.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.055 seconds
[2025-10-29T02:20:17.492+0000] {processor.py:161} INFO - Started process (PID=818) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:20:17.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:20:17.497+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:20:17.496+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:20:17.505+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:20:17.503+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:20:17.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:20:17.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.047 seconds
[2025-10-29T02:20:47.757+0000] {processor.py:161} INFO - Started process (PID=819) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:20:47.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:20:47.766+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:20:47.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:20:47.783+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:20:47.774+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:20:47.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:20:47.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.069 seconds
[2025-10-29T02:21:18.096+0000] {processor.py:161} INFO - Started process (PID=820) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:21:18.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:21:18.103+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:21:18.102+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:21:18.132+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:21:18.127+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:21:18.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:21:18.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.104 seconds
[2025-10-29T02:21:48.423+0000] {processor.py:161} INFO - Started process (PID=821) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:21:48.427+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:21:48.434+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:21:48.433+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:21:48.443+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:21:48.441+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:21:48.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:21:48.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.077 seconds
[2025-10-29T02:22:18.757+0000] {processor.py:161} INFO - Started process (PID=822) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:22:18.759+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:22:18.764+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:22:18.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:22:18.775+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:22:18.772+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:22:18.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:22:18.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.062 seconds
[2025-10-29T02:22:49.036+0000] {processor.py:161} INFO - Started process (PID=823) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:22:49.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:22:49.049+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:22:49.048+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:22:49.077+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:22:49.073+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:22:49.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:22:49.137+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.117 seconds
[2025-10-29T02:23:19.349+0000] {processor.py:161} INFO - Started process (PID=824) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:23:19.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:23:19.359+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:23:19.358+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:23:19.372+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:23:19.369+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:23:19.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:23:19.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.085 seconds
[2025-10-29T02:23:49.675+0000] {processor.py:161} INFO - Started process (PID=825) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:23:49.677+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:23:49.681+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:23:49.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:23:49.689+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:23:49.687+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:23:49.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:23:49.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.059 seconds
[2025-10-29T02:24:19.956+0000] {processor.py:161} INFO - Started process (PID=826) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:24:19.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:24:19.961+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:24:19.961+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:24:19.970+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:24:19.968+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:24:19.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:24:19.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.050 seconds
[2025-10-29T02:24:50.210+0000] {processor.py:161} INFO - Started process (PID=827) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:24:50.211+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:24:50.215+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:24:50.215+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:24:50.224+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:24:50.222+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:24:50.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:24:50.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.050 seconds
[2025-10-29T02:25:20.495+0000] {processor.py:161} INFO - Started process (PID=828) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:25:20.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:25:20.501+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:25:20.501+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:25:20.509+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:25:20.507+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:25:20.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:25:20.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.050 seconds
[2025-10-29T02:25:50.851+0000] {processor.py:161} INFO - Started process (PID=829) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:25:50.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:25:50.859+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:25:50.858+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:25:50.871+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:25:50.869+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:25:50.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:25:50.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.069 seconds
[2025-10-29T02:26:21.168+0000] {processor.py:161} INFO - Started process (PID=830) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:26:21.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:26:21.176+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:26:21.175+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:26:21.187+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:26:21.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:26:21.187+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:26:21.223+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.071 seconds
[2025-10-29T02:26:51.415+0000] {processor.py:161} INFO - Started process (PID=831) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:26:51.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:26:51.422+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:26:51.422+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:26:51.434+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:26:51.428+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:26:51.436+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:26:51.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.064 seconds
[2025-10-29T02:34:56.278+0000] {processor.py:161} INFO - Started process (PID=847) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:34:56.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:34:56.285+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:34:56.284+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:34:56.299+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:34:56.293+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:34:56.301+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:34:56.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.073 seconds
[2025-10-29T02:35:26.625+0000] {processor.py:161} INFO - Started process (PID=848) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:35:26.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:35:26.633+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:35:26.632+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:35:26.643+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:35:26.641+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:35:26.644+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:35:26.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.072 seconds
[2025-10-29T02:35:56.916+0000] {processor.py:161} INFO - Started process (PID=849) to work on /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:35:56.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/loan_doc_pipeline_dag.py for tasks to queue
[2025-10-29T02:35:56.922+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:35:56.922+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:35:56.933+0000] {logging_mixin.py:188} INFO - [2025-10-29T02:35:56.930+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/loan_doc_pipeline_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/loan_doc_pipeline_dag.py", line 25, in <module>
    from scripts.extraction_pipeline.config import setup_logger
ModuleNotFoundError: No module named 'scripts.extraction_pipeline'
[2025-10-29T02:35:56.934+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/loan_doc_pipeline_dag.py
[2025-10-29T02:35:56.981+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/loan_doc_pipeline_dag.py took 0.079 seconds
